/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Application;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-08-09T05:32:42.466Z[GMT]")
@Api(value = "updateApplication", description = "the updateApplication API")
public interface UpdateApplicationApi {

    @ApiOperation(value = "Updates an existing mortgage application in the store", nickname = "updateApplication", notes = "", tags={ "Mortgage Application", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Application updated successfully"),
        @ApiResponse(code = 405, message = "Invalid Request") })
    @RequestMapping(value = "/updateApplication",
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> updateApplication(@ApiParam(value = "Mortgage application that needs to be updated to the store" ,required=true )  @Valid @RequestBody Application body
);

}

